apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  labels:
    app: nginx-f8
  name: nginx-f8
  namespace: ba-test
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      requests:
        cpu: 500m
        memory: 200Mi