apiVersion: v1
kind: LimitRange
metadata:
  name: k8smanager
  namespace: ba-test
spec:
  limits:
    - max:
        cpu: "700m"
        memory: 800Mi
      min:
        cpu: 100m
        memory: 100Mi
      type: Container