apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nginx-f12
  name: nginx-f12
  namespace: ba-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-f12
  template:
    metadata:
      labels:
        app: nginx-f12
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 1m
            memory: 128Mi      