apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-f7
  name: nginx-f7
  namespace: ba-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-f7
  template:
    metadata:
      labels:
        app: nginx-f7
    spec:
      containers:
      - image: nginx
        name: nginx-f7
        resources: 
          limits: 
            cpu: 1
            memory: 128Mi
      restartPolicy: Always
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: topology.kubernetes.io/zone