apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nginx-f9
  name: nginx-f9
  namespace: ba-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-f9
  template:
    metadata:
      labels:
        app: nginx-f9
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
          requests:
            cpu: 200m
            memory: 500Mi