apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nginx-f2
  name: nginx-f2
  namespace: ba-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-f2
  template:
    metadata:
      labels:
        app: nginx-f2
    spec:
      containers:
      - image: webserver
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            cpu: 200m
            memory: 100Mi  
          requests:
            cpu: 200m
            memory: 100Mi