apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nginx-f14
  name: nginx-f14
  namespace: ba-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-f14
  template:
    metadata:
      labels:
        app: nginx-f14
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 80Mi 