apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: f2-memory-stress
  namespace: ms-demo
spec:
  mode: one
  selector:
    labelSelectors:
      'app': 'cartservice'
  stressors:
    memory:
      workers: 1
      size: '180MB'
      oomScoreAdj: -1000
  duration: 600s