apiVersion: v1
kind: Node
metadata:
  name: minikube
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoSchedule
    key: key1
    value: value1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-f3
  name: nginx-f3
  namespace: ba-test
spec:
  selector:
    matchLabels:
      app: nginx-f3
  template:
    metadata:
      labels:
        app: nginx-f3
    spec:
      containers:
      - image: nginx
        name: nginx-f3
        resources: 
          limits: 
            cpu: 200m
            memory: 100Mi
      restartPolicy: Always